repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: ["--fix"]
        exclude: '(__pycache__/|\.pyc$|^dist/|^docs/build/)'

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: ["-r", "optics_framework"]
        exclude: '(__pycache__/|\.pyc$|^dist/|^docs/build/|tests/)'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '(__pycache__/|\.pyc$|^dist/|^docs/build/)'
      - id: end-of-file-fixer
        exclude: '(__pycache__/|\.pyc$|^dist/|^docs/build/)'
      - id: check-yaml
        exclude: '(__pycache__/|\.pyc$|^dist/|^docs/build/|mkdocs\.yml)'
      - id: check-json
        exclude: '(__pycache__/|\.pyc$|^dist/|^docs/build/)'

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.4.1
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.3
    hooks:
      - id: gitleaks
        exclude: '(__pycache__/|\.pyc$|^dist/|^docs/build/|tests/)'
